# Generated by Django 4.0 on 2022-01-14 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('experimenting', '0003_remove_ticket_users_ticket_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='submitter', to='auth.user'),
        ),
    ]
