# Generated by Django 4.0 on 2022-01-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experimenting', '0004_alter_ticket_modified_by_alter_ticket_submitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='personnel_assigned',
        ),
    ]
