# Generated by Django 4.0 on 2022-01-14 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('experimenting', '0005_rename_users_project_personnel_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='personnel_assigned',
            new_name='assigned_personnel',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_developer', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority_level',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NW', 'New'), ('OP', 'Open'), ('IP', 'In Progress'), ('RS', 'Resolved'), ('AIR', 'Additional Info Required')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('BG', 'Bugs/Errors'), ('FR', 'Feature Requests'), ('OC', 'Other Comments'), ('TDR', 'Training / Document Requests')], max_length=20),
        ),
    ]
