# Generated by Django 4.0 on 2022-01-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenting', '0006_rename_personnel_assigned_project_assigned_personnel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='attachment',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
