# Generated by Django 4.0 on 2022-01-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenting', '0007_remove_file_url_file_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='attachment',
            field=models.FileField(blank=True, upload_to='tickets/'),
        ),
    ]
