# Generated by Django 4.0 on 2022-01-23 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('experimenting', '0009_comment_created_comment_updated_file_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_developer',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_developer', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submitter',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='submitter', to='auth.user'),
        ),
    ]
