# Generated by Django 4.0 on 2022-01-27 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('experimenting', '0010_alter_ticket_assigned_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(default='cabezon', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_developer', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='submitter', to='auth.user'),
        ),
    ]
