# Generated by Django 4.0 on 2022-01-28 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('experimenting', '0011_file_description_alter_ticket_assigned_developer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('new_developer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='auth.user')),
                ('old_developer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='old_dev', to='auth.user')),
            ],
        ),
    ]
