# Generated by Django 4.0 on 2022-01-28 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('experimenting', '0012_tickethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='new_developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='old_developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='old_dev', to='auth.user'),
        ),
    ]
