# Generated by Django 4.0 on 2022-01-28 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimenting', '0013_alter_tickethistory_new_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='experimenting.ticket'),
            preserve_default=False,
        ),
    ]
