# Generated by Django 4.0 on 2022-01-29 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experimenting', '0016_remove_userrole_users_userrole_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='role',
            new_name='roles',
        ),
    ]
