# Generated by Django 4.0 on 2022-01-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experimenting', '0017_rename_role_userrole_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
